/// Role of a chat participant.
enum ChatRole {
  /// A message sent by the human user.
  user,

  /// A message generated by the Komo AI bot.
  bot,
}

/// Immutable domain model for a single chat message.
///
/// NOTE: The backend [MessageRead] schema omits `created_at`, so this model
/// carries no timestamp. Display ordering follows the backend's list order.
class ChatMessage {
  const ChatMessage({
    required this.id,
    required this.role,
    required this.content,
  });

  /// Server-assigned message id.
  final String id;

  /// Who sent this message — [ChatRole.user] or [ChatRole.bot].
  final ChatRole role;

  /// Raw text content of the message.
  final String content;

  @override
  String toString() => 'ChatMessage(id: $id, role: $role, content: $content)';
}
